name: "Get version"
description: "Gets the version number from GitHub environment"

runs:
  using: "composite"

  steps:
    - run: |
        if [[ "$GITHUB_REF" == *"tags/v"* ]]; then
          version="${GITHUB_REF_NAME#v}"
          echo "IEUM_VERSION=$version" >> "$GITHUB_ENV"
          echo "IEUM_PACKAGE_VERSION=$version" >> "$GITHUB_ENV"
        else
          echo "IEUM_VERSION=$(git describe --tags --always --dirty)" >> "$GITHUB_ENV"
          echo "IEUM_PACKAGE_VERSION=continuous" >> "$GITHUB_ENV"
        fi
      shell: bash
